# Generated by Django 4.0.2 on 2023-10-16 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_product_product_image_delete_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='desc',
            field=models.TextField(default='product details not found', verbose_name='Product Description'),
        ),
    ]
