# Generated by Django 4.0.2 on 2023-10-16 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0007_alter_product_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='orders',
            field=models.CharField(blank=True, default='0', max_length=50, null=True, verbose_name='Orders for Product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sold',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sold Quantity'),
        ),
    ]
