# Generated by Django 4.0.2 on 2023-10-17 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0008_alter_product_orders_alter_product_sold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerprofile',
            name='img',
            field=models.ImageField(blank=True, default='', null=True, upload_to='seller-profiles', verbose_name='Seller Profile Img'),
        ),
    ]
